builders:
  genui_gen:
    import: "package:genui_gen_builder/builder.dart"
    builder_factories: ["genUiGenBuilder"]
    build_extensions: {".dart": [".genui.dart"]}
    auto_apply: dependents
    build_to: source
